name: xl
description: >
  Implement accelerometer and pointer or touch fueled parallax
  animations with a bespoke XL layering paradigm. Gyroscope supported.
version: 0.9.1
repository: https://github.com/Zabadam/xl
issue_tracker: https://github.com/Zabadam/xl/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^1.0.1

dev_dependencies:
  very_good_analysis: ^1.0.4
  flutter_test:
    sdk: flutter

flutter: null
